### ISSUE TITLE
Info about using uClib-ng on WDR4900

### ISSUE THREAD

**Issue by bouwew** [gwlim/mpc85xx-lede-patch#1]
Hi Gwlim,

Just in case you are interested, I found this info:
http://lists.infradead.org/pipermail/lede-dev/2016-June/001145.html

I combined the info in the link above with this change:

--- target/linux/mpc85xx/Makefile     (revision 47513)
+++ target/linux/mpc85xx/Makefile	(working copy)
@@ -10,7 +10,7 @@
BOARD:=mpc85xx
BOARDNAME:=Freescale MPC85xx
CPU_TYPE:=8540
-FEATURES:=squashfs
+FEATURES:=spe_fpu squashfs
MAINTAINER:=Imre Kaloz <kaloz@openwrt.org>
SUBTARGETS=generic p1020

After that I ran a make defconfig, followed by make menuconfig, selected uClib-ng and unselected using softfloat.

After a compile-run, with some of your older mpc85xx patches included, I loaded the firmware and it's running fine :)

**Comment by gwlim** [comment]
Yea but that will mean it is not supported upstream.
MUSL is really a headache for PowerPC e500v2 as SPE is not supported.
This causes a lot of issue as Linux Kernel has alot of optimization crypto code for SPE

**Comment by bouwew** [comment]
Since the WDR4900 V1 is no longer actively supported, I would be positively surprised to see it taken to kernel 4.9, I guess we're on our own trying to keep it running at full performance ;P

**Comment by bouwew** [comment]
UPDATE 2: No, makes no difference.

I tried with: -mcpu=8548 -mspe -misel -mabi=spe -fomit-frame-pointer -fno-caller-saves -mfloat-gprs=double -mno-longcall -pthread -mtls-markers

UPDATE: I guess not!
Just compared a MUSL-build -latest trunk with most of your patches applied- to an uClibc-ng-build -same files&setting&patches as the MUSL-build but now with uClibc-ng and with the CONFIG...SPE... parameters " = y" in ../mpc85xx/config-4.4. This gives roughly a 15% increase in performance when performing "openssl speed md5/aes-128-cbc/eas-256-cbc" tests.
Could I benefit even more from the gcc-settings that you use in the barrier breaker patch?

Now used: -mcpu=8548 -misel -fomit-frame-pointer -fno-caller-saves -mfloat-gprs=double -mno-longcall -pthread -mtls-markers

BB-settings: -mcpu=8548 -mspe -misel -mabi=spe -fomit-frame-pointer -fno-caller-saves -mfloat-gprs=double -mno-longcall -pthread -mtls-markers -mmultiple -mstring

OLD TEXT: On another note, I noticed you disabled SPE-support in ../mpc85xx/config-4.4. Would that not give a negative effect? As far as I have understood MUSL supports the SPE-functions via emulation/soft-float?

**Comment by bouwew** [comment]
Also, FYI, I'm attempting the build with kernel 4.9.
The patches required very minor changes. I'm building now, first attempt. Will let you know the results, if you are interested?

**Comment by gwlim** [comment]
Hi if you noticed I added OpenSSL PowerPC Assembly Optimization patches, can you check if this is faster or slower than add uclibc-ng and building the Kernel with SPE using the OpenSSL Benchmark?
I try to stick to upstream otherwise I have to maintain more stuff

**Comment by gwlim** [comment]
`
| r3301 | 1.0.2k | 80568180 | 22590750 | 16591900 | 14179220 | 10618460 | 3770810 | 19160910 | 16955300 | 15194290 | 14.2 | 554.1 48.8 | 44.3 |`

**Comment by bouwew** [comment]
Of which openssl speed xyz command was this the output of?

**Comment by bouwew** [comment]
My previous results:

Result with MUSL:

root@router:~# openssl speed md5
Doing md5 for 3s on 16 size blocks: 853767 md5's in 2.98s
Doing md5 for 3s on 64 size blocks: 728826 md5's in 2.94s
Doing md5 for 3s on 256 size blocks: 514140 md5's in 2.92s
Doing md5 for 3s on 1024 size blocks: 226887 md5's in 2.69s
Doing md5 for 3s on 8192 size blocks: 38500 md5's in 2.89s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-musl-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include/fortify -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_musl/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
md5               4583.98k    15865.60k    45075.29k    86368.88k   109132.18k

root@router:~# openssl speed aes-128-cbc
Doing aes-128 cbc for 3s on 16 size blocks: 2967219 aes-128 cbc's in 2.88s
Doing aes-128 cbc for 3s on 64 size blocks: 832545 aes-128 cbc's in 2.88s
Doing aes-128 cbc for 3s on 256 size blocks: 220580 aes-128 cbc's in 2.90s
Doing aes-128 cbc for 3s on 1024 size blocks: 55473 aes-128 cbc's in 2.95s
Doing aes-128 cbc for 3s on 8192 size blocks: 6915 aes-128 cbc's in 2.96s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-musl-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include/fortify -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_musl/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      16484.55k    18501.00k    19471.89k    19255.71k    19137.73k

root@router:~# openssl speed aes-256-cbc
Doing aes-256 cbc for 3s on 16 size blocks: 1155180 aes-256 cbc's in 1.39s
Doing aes-256 cbc for 3s on 64 size blocks: 572550 aes-256 cbc's in 2.51s
Doing aes-256 cbc for 3s on 256 size blocks: 174807 aes-256 cbc's in 2.97s
Doing aes-256 cbc for 3s on 1024 size blocks: 43900 aes-256 cbc's in 2.96s
Doing aes-256 cbc for 3s on 8192 size blocks: 5509 aes-256 cbc's in 2.98s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-musl-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_musl/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include/fortify -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_musl/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_musl/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-256 cbc      13297.04k    14598.88k    15067.54k    15187.03k    15144.20k

Result with uClib-ng:

root@router:~# openssl speed md5
Doing md5 for 3s on 16 size blocks: 948588 md5's in 2.96s
Doing md5 for 3s on 64 size blocks: 795039 md5's in 2.95s
Doing md5 for 3s on 256 size blocks: 545914 md5's in 2.94s
Doing md5 for 3s on 1024 size blocks: 241609 md5's in 2.94s
Doing md5 for 3s on 8192 size blocks: 39152 md5's in 2.96s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-uclibcspe-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_uClibc/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
md5               5127.50k    17248.30k    47535.37k    84152.25k   108355.81k
root@router:~# openssl speed aes-128-cbc
Doing aes-128 cbc for 3s on 16 size blocks: 3411966 aes-128 cbc's in 2.94s
Doing aes-128 cbc for 3s on 64 size blocks: 953466 aes-128 cbc's in 2.94s
Doing aes-128 cbc for 3s on 256 size blocks: 243285 aes-128 cbc's in 2.94s
Doing aes-128 cbc for 3s on 1024 size blocks: 61623 aes-128 cbc's in 2.94s
Doing aes-128 cbc for 3s on 8192 size blocks: 7730 aes-128 cbc's in 2.94s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-uclibcspe-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_uClibc/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-128 cbc      18568.52k    20755.72k    21184.00k    21463.25k    21538.83k
root@router:~# openssl speed aes-256-cbc
Doing aes-256 cbc for 3s on 16 size blocks: 2817570 aes-256 cbc's in 2.96s
Doing aes-256 cbc for 3s on 64 size blocks: 765308 aes-256 cbc's in 2.96s
Doing aes-256 cbc for 3s on 256 size blocks: 197011 aes-256 cbc's in 2.96s
Doing aes-256 cbc for 3s on 1024 size blocks: 49365 aes-256 cbc's in 2.92s
Doing aes-256 cbc for 3s on 8192 size blocks: 6199 aes-256 cbc's in 2.94s
OpenSSL 1.0.2k  26 Jan 2017
built on: reproducible build, date unspecified
options:bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) aes(partial) blowfish(ptr)
compiler: powerpc-openwrt-linux-uclibcspe-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/target-powerpc_8540_uClibc/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/usr/include -I/home/bouwe/LEDE/source/staging_dir/toolchain-powerpc_8540_gcc-6.3.0_uClibc/include -znow -zrelro -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -mcpu=8548 -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/bouwe/LEDE/source/build_dir/target-powerpc_8540_uClibc/openssl-1.0.2k:openssl-1.0.2k -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -fPIC -I/home/bouwe/LEDE/source/package/libs/openssl/include -ffunction-sections -fdata-sections -fomit-frame-pointer -Wall
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes
aes-256 cbc      15230.11k    16547.20k    17038.79k    17311.56k    17272.86k

**Comment by bouwew** [comment]
The strikeout-part of the above text is not supposed to be like that...

**Comment by gwlim** [comment]
I use the command from this
https://wiki.openwrt.org/doc/howto/benchmark.openssl

**Comment by bouwew** [comment]
`| r3770 | 1.0.2k | 83962140 | 24763560 | 17747610 | 13325680 | 11087680 | 3730730 | 21551180 | 18975270 | 17128820 | 14.3 | 548.9 48.2 | 44.3 |`

**Comment by bouwew** [comment]
The above results are for my uClibc-ng build.

**Comment by bouwew** [comment]
Could I use your OpenSSL PowerPC Assembly Optimization patches on my uClibc-ng build? Or would they have no effect?

**Comment by gwlim** [comment]
It is already inside.
Not quit sure about effects, I guess if you use ASM instead it will skip the SPE code.
Anyway SPE is still a bit faster than ASM
