### ISSUE TITLE
tx-vlan-offload is off

### ISSUE THREAD

**Issue by gwlim** [gwlim/mpc85xx-lede-patch#3]
ethtool show
rx-vlan-offload is on 
but
tx-vlan-offload is off

**Comment by gwlim** [comment]
Enabled tx-vlan-offload but need to check performance.

**Comment by bouwew** [comment]
Nice to read that you got it working!

Have been trying to build, but I don't see shortcut-fe or fastpath in my system-log.
What do I need to enable in make menuconfig?

kmod-shortcut-fe I guess? And not the other 2 kmod-shortcut-fe-... options?
What about kmod-qca-ssdk-nohnat? Not required?

It would be good if you could add this kind of information in your README-files :)

**Comment by gwlim** [comment]
Kernel Modules > Network Support >
kmod-shortcut-fe
fast-classifier
fast-classifier-cm
You can also find the completed builds here
https://github.com/gwlim/Fast-Path-LEDE-OpenWRT/tree/master/Fast-Path/July-2017

**Comment by bouwew** [comment]
Thanks!!
