### ISSUE TITLE
Update Repo

### ISSUE THREAD

**Issue by dag03tsc** [gwlim/mpc85xx-lede-patch#5]
Hi @gwlim! Pretty cool work! But this repo is pretty behind the current openwrt trunk and it has a bunch of broken and outdated patches.

It'd be awesome if you could push an update with current patch script, patches and make .config file you're applying on your last [WDR4900v1-p1014 build](https://github.com/gwlim/openwrt-sfe-flowoffload/tree/master/JAN-2019/openwrt-sfe-flowoffload-normal/TP-Link%20WDR4900v1-p1014).

I love that build but I need to include some more packages and kmods due to requirements of my ISP's setting (Movistar). These include **bird4, kmod-bridge, kmod-ipt-nathelper-rtsp, kmod-nf-conntrack-netlink and omcproxy** among others for fullworking WAN, VOIP and IPTV services.

I've been using for a year a v17.01.4 build that I managed to patch with this repo after manually merging #4 and moving both [012](https://github.com/gwlim/mpc85xx-lede-patch/blob/lede-17.01/patch/012-fix-upstream-feed.patch) and [060](https://github.com/gwlim/mpc85xx-lede-patch/blob/lede-17.01/patch/060-change-luci-version.patch) patches to broken folder. I must say it has worked flawlessly since then!

I've tried the v18.06.1 base release but the performance is crappy and almost all of this patches are broken on v18 and v19. I've successfully ported some to v18.06.1 and the performance increases a bit, but I'm far far away from your last build yet, and, probably, I could never ever get to it! XD

Looking forward the update. Thanks a lot for this amazing work! Greetings and happy holidays!

**Comment by gwlim** [comment]
To understand how NAT affect performance follow this test.
https://openwrt.org/docs/guide-user/perf_and_log/benchmark.nat
